apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: base-apps-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/alertmanager  # директория на узле