apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: grafina-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: grafina-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/grafana
