apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: loki-sc
  persistentVolumeReclaimPolicy: Retain # можно поменять на Delete
  hostPath:
    path: /mnt/data/loki # на узле будет эта папка
