apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: base-apps-storage
  persistentVolumeReclaimPolicy: Retain # можно поменять на Delete
  hostPath:
    path: /mnt/data/loki # на узле будет эта папка
