apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: loki-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: loki-pv
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: base-apps-storage
  persistentVolumeReclaimPolicy: Retain # можно поменять на Delete
  hostPath:
    path: /mnt/data/loki # на узле будет эта папка
