apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometeos-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: prometeos-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/prometheus