apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: base-apps-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/prometheus