apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: trefeik-sc
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: Immediate

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: trefeik-sc
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/traefik
