apiVersion: v1
kind: PersistentVolume
metadata:
  name: traefik-pv
spec:
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: base-apps-storage
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/traefik
