service:
  enabled: true
  type: NodePort
  annotations: {}
  labels: {}
  spec: {}

ports:
  web:
    port: 8000
    expose:
      default: true
    exposedPort: 80
    protocol: TCP
    nodePort: 30001 # 👈 свой NodePort

  websecure:  
    port: 8443
    expose:
      default: true
    exposedPort: 443
    protocol: TCP
    nodePort: 30000 # 👈 свой NodePort

api:
  dashboard: true
  insecure: true # только для тестов, иначе нужен auth

ingressRoute:
  dashboard:
    enabled: true
    entryPoints: ["web"]
    insecure: true
    matchRule: "PathPrefix(`/dashboard`) || PathPrefix(`/api`)"
    services: [{ "kind": "TraefikService", "name": "api@internal" }]

deployment:
  replicas: 1
  serviceAccount:
    create: true
    name: traefik
  additionalArguments:
    - "--api.dashboard=true"
    - "--api.insecure=true"
    - "--entrypoints.web.address=:80"
    - "--entrypoints.websecure.address=:443"
    - "--providers.kubernetescrd"
    - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
    - "--certificatesresolvers.myresolver.acme.httpchallenge.entryPoint=web"
    - "--certificatesresolvers.myresolver.acme.email=andrey.chizhov.dev@gmail.com"
    - "--certificatesresolvers.myresolver.acme.storage=/data/acme.json"
    - "--log.level=DEBUG"
    - "--accesslog=true"

persistence:
  enabled: true
  size: 50Mi
  storageClass: trefeik-sc
  mountPath: /data
  accessMode: ReadWriteOnce
